package com.cytech.application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

import java.io.IOException;

import com.cytech.gestionFichiers.GestionJSON;
import com.cytech.utilisateur.Client;

import javafx.event.ActionEvent;

public class ClientMenuController {
	
	@FXML
	private Label TitleLabel;
	
	private Stage stage;
	private Scene scene;
	private Parent root;
	// Event Listener on Button.onAction
	@FXML
	public void voirlisteCommande(ActionEvent event) {
		Client.voirCommande(MainSceneController.nomClient);
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnclickclient(ActionEvent event) throws IOException {
		 root = FXMLLoader.load(getClass().getClassLoader().getResource("com\\\\cytech\\\\interfaces\\\\ClientScene.fxml"));
		 stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		 scene = new Scene(root);
		 stage.setScene(scene);
		 stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void passerCommande(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void displayName(String username) {
		TitleLabel.setText("Bonjour " + username);
	}
}
